# Generated by Django 5.0.6 on 2024-05-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('python_code', models.TextField(max_length=4000)),
                ('java_code', models.TextField(max_length=4000)),
                ('cpp_code', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('python_code', models.TextField(max_length=4000)),
                ('java_code', models.TextField(max_length=4000)),
                ('cpp_code', models.TextField(max_length=4000)),
            ],
        ),
    ]
